function initUnitsLibrary() {
    unitsLibrary = [
        {
            'id' : 0,
            'type' : 'hero',        
            'name' : 'Astral Mage',
            'imagePath' : '/images/heroes/astral_mage.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 6,
            'currentAP' : 6,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7
        },
        {
            'id' : 1,
            'type' : 'hero',        
            'name' : 'Air Mage',
            'imagePath' : '/images/heroes/air_mage.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 7,
            'currentAP' : 7,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7
        },
        {
            'id' : 2,
            'type' : 'hero',        
            'name' : 'Fire Mage',
            'imagePath' : '/images/heroes/fire_mage.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 5,
            'currentAP' : 5,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7 
        },
        {
            'id' : 3,
            'type' : 'hero',        
            'name' : 'Water Mage',
            'imagePath' : '/images/heroes/water_mage.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 5,
            'currentAP' : 5,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7
        },
        {
            'id' : 4,
            'type' : 'hero',        
            'name' : 'Earth Mage',
            'imagePath' : '/images/heroes/earth_mage.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 2,
            'currentAP' : 2,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7
        },
        {
            'id' : 5,
            'type' : 'hero',        
            'name' : 'White Mage',
            'imagePath' : '/images/heroes/white_mage.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 4,
            'currentAP' : 4,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7 
        },
        {
            'id' : 6,
            'type' : 'hero',        
            'name' : 'Black Mage',
            'imagePath' : '/images/heroes/black_mage.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 4,
            'currentAP' : 4,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7 
        },
        {
            'id' : 7,
            'type' : 'hero',        
            'name' : 'Summoner Mage',
            'imagePath' : '/images/heroes/summoner_mage.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 5,
            'currentAP' : 5,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7 
        },
        {
            'id' : 8,
            'type' : 'hero',        
            'name' : 'Bowman',
            'imagePath' : '/images/heroes/bowman.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 5,
            'currentAP' : 5,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7
        },
        {
            'id' : 9,
            'type' : 'hero',        
            'name' : 'Shieldman',
            'imagePath' : '/images/heroes/shieldman.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 3,
            'currentAP' : 3,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7
        },
        {
            'id' : 10,
            'type' : 'hero',        
            'name' : 'Swordman',
            'imagePath' : '/images/heroes/swordman.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 4,
            'currentAP' : 4,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7
        },
        {
            'id' : 11,
            'type' : 'hero',        
            'name' : 'Daggerman',
            'imagePath' : '/images/heroes/daggerman.jpg', 
            'team' : undefined,  
            'indexes' : { x : undefined, y : undefined },
            'baseHP' : 7,
            'currentHP' : 7,
            'baseAP' : 5,
            'currentAP' : 5,
            'baseDamage' : 7,
            'currentDamage' : 7,
            'baseAttackDistance' : 7,
            'currentAttackDistance' : 7
        }
    ];
}

function initSkillsLibrary() {
    skillsLibrary = [
        
    ];
}