units = [
    {
        'id' : 0,
        'type' : 'hero',        
        'name' : 'Astral Mage',
        'imagePath' : '/images/heroes/astral_mage.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7
    },
    {
        'id' : 1,
        'type' : 'hero',        
        'name' : 'Air Mage',
        'imagePath' : '/images/heroes/air_mage.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7
    },
    {
        'id' : 2,
        'type' : 'hero',        
        'name' : 'Fire Mage',
        'imagePath' : '/images/heroes/fire_mage.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7 
    },
    {
        'id' : 3,
        'type' : 'hero',        
        'name' : 'Water Mage',
        'imagePath' : '/images/heroes/water_mage.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7
    },
    {
        'id' : 4,
        'type' : 'hero',        
        'name' : 'Earth Mage',
        'imagePath' : '/images/heroes/earth_mage.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7
    },
    {
        'id' : 5,
        'type' : 'hero',        
        'name' : 'White Mage',
        'imagePath' : '/images/heroes/white_mage.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7 
    },
    {
        'id' : 6,
        'type' : 'hero',        
        'name' : 'Black Mage',
        'imagePath' : '/images/heroes/black_mage.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7 
    },
    {
        'id' : 7,
        'type' : 'hero',        
        'name' : 'Summoner Mage',
        'imagePath' : '/images/heroes/summoner_mage.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7 
    },
    {
        'id' : 8,
        'type' : 'hero',        
        'name' : 'Bowman',
        'imagePath' : '/images/heroes/bowman.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7
    },
    {
        'id' : 9,
        'type' : 'hero',        
        'name' : 'Shieldman',
        'imagePath' : '/images/heroes/shieldman.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7
    },
    {
        'id' : 10,
        'type' : 'hero',        
        'name' : 'Swordman',
        'imagePath' : '/images/heroes/swordman.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7
    },
    {
        'id' : 11,
        'type' : 'hero',        
        'name' : 'Daggerman',
        'imagePath' : '/images/heroes/daggerman.jpg', 
        'team' : undefined,  
        'indexes' : { x : undefined, y : undefined },
        'baseHP' : 7,
        'currentHP' : 7,
        'baseAP' : 7,
        'currentAP' : 7,
        'baseDamage' : 7,
        'currentDamage' : 7,
        'baseAttackDistance' : 7,
        'currentAttackDistance' : 7
    }
];